# https://github.com/actions/deploy-pages#usage
name: Deploy to GitHub Pages
on:
  push:
    tags:
      - '*'  # Runs on any tag push
jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: pnpm install

      - name: Build 
        run: NUXT_APP_BASE_URL=/iiot_toolbox/ pnpm dlx nuxt build --preset github_pages        

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.output/public

      - name: Generate changelog
        run: pnpm dlx changelogen > RELEASE_CHANGELOG.md

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.ref_name }}
          bodyFile: RELEASE_CHANGELOG.md

  deploy:
    needs: build_and_release
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github_pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
